<a href="https://colab.research.google.com/github/abhisripathi/ML-Python-project/blob/main/Purnabhishek_Sripathi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing libraries**

In [48]:
import pandas as pd
import numpy as np

We use iris data included in scikit-learn.

we use load_iris() function that loads iris dataset. 

In [49]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [50]:
print("keys of iris_dataset: \n{}" .format(iris_dataset.keys()))


keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


The value of the key **DESCR** is a short description of the dataset.

Let's see what it contains.

In [51]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [52]:
print("Target names: {}" .format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [53]:
print("Feature names: \n{}" .format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [54]:
print("Type of data: {}" .format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [55]:
print("Shape of data {}" .format(iris_dataset['data'].shape))

Shape of data (150, 4)


In [56]:
print("First five columns of data :\n{}" .format(iris_dataset['data'][:5]))

First five columns of data :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [57]:
print("Type of target: {}" .format(iris_dataset['target']))

Type of target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [58]:
print("Shape of target: {}" .format(iris_dataset['target'].shape))

Shape of target: (150,)


Now we do Training and Testing of data.
Here we import train-test_split() method from sklearn library to divide the data set into subsets.

X_train X-test represents "Features", and y-train, y_test represents "Labels".
X_train contains 75% of the rows of the dataset, and X_test contains the remaining 25%.

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

Let's see the shape

In [60]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape)) 

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


We will make a Machine Learning Model. 
We use K-nearest neighbor algorithm

The k-nearest neighbors (KNN) algorithm  a simple, supervised machine learning algorithm that can be used to solve both classification and regression problems.

The most important parameter is number of neighbors it is set to 1.

In [61]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

Now we will Train the data.

It is like giving book to student to learn/study.

In [62]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Making Predictions.**

Whether perticular prediction is correct or wrong.


New species of flower data is sent.

In [63]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


scikit-learn always expects two-dimensional arrays for the data.

**Doing prediction.**

We will call the predict method of the knn object.

In [64]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
    iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


**Prediction by model**

test set predictions

In [65]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


These are the test set predictions from our model.

**Need to check whether the predictions are correct or not**

we do mean of everything to get accuracy

In [66]:
print("Test set score:{}" .format(np.mean(y_pred==y_test)))

Test set score:0.9736842105263158
